ETHNICITY_CODES = {
    "fa_IR": "Persian - Iran",
    "he_IL": "Hebrew - Israel",
    "cs_CZ": "Czech - Czech Republic",
    "da_DK": "Danish - Denmark",
    "de_AT": "German - Austria",
    "de_CH": "German - Switzerland",
    "de_DE": "German - Germany",
    "el_GR": "Greek - Greece",
    "en_CA": "English - Canada",
    "en_US": "English - United States",
    "en_GB": "English - United Kingdom",
    "en_IE": "English - Ireland",
    "es_ES": "Spanish - Spain",
    "fi_FI": "Finnish - Finland",
    "fr_CA": "French - Canada",
    "fr_CH": "French - Switzerland",
    "fr_FR": "French - France",
    "hr_HR": "Croatian - Croatia",
    "hu_HU": "Hungarian - Hungary",
    "hy_AM": "Armenian - Armenia",
    "it_IT": "Italian - Italy",
    "nl_BE": "Dutch - Belgium",
    "nl_NL": "Dutch - Netherlands",
    "no_NO": "Norwegian - Norway",
    "pl_PL": "Polish - Poland",
    "pt_PT": "Portuguese - Portugal",
    "ro_RO": "Romanian - Romania",
    "ru_RU": "Russian - Russia",
    "sk_SK": "Slovak - Slovakia",
    "sv_SE": "Swedish - Sweden",
    "uk_UA": "Ukrainian - Ukraine",
    "ja_JP": "Japanese - Japan",
    "ko_KR": "Korean - South Korea",
    "zh_CN": "Chinese - China",
    "zh_TW": "Chinese - Taiwan",
    "en_IN": "English - India",
    "az_AZ": "Azerbaijani - Azerbaijan",
    "en_BD": "English - Bangladesh",
    "bn_BD": "Bengali - Bangladesh",
    "hi_IN": "Hindi - India",
    "ka_GE": "Georgian - Georgia",
    "ne_NP": "Nepali - Nepal",
    "ta_IN": "Tamil - India",
    "en_MS": "English - Malaysia",
    "en_PH": "English - Philippines",
    "fil_PH": "Filipino - Philippines",
    "id_ID": "Indonesian - Indonesia",
    "th_TH": "Thai - Thailand",
    "tl_PH": "Tagalog - Philippines",
    "vi_VN": "Vietnamese - Vietnam",
    "es_AR": "Spanish - Argentina",
    "es_CL": "Spanish - Chile",
    "es_CO": "Spanish - Colombia",
    "es_MX": "Spanish - Mexico",
    "pt_BR": "Portuguese - Brazil",
    "zu_ZA": "Zulu - South Africa",
    "en_AU": "English - Australia",
    "en_NZ": "English - New Zealand",
}
